// Avatar — renders the build-time optimized portrait as a <picture> with a webp
// source and jpg fallback. Deliberately NOT next/image: the site is a static
// export with images.unoptimized:true, so we ship the pre-baked assets emitted by
// scripts/optimize-portrait.mjs (public/portrait/jake-{128,256,512}.{webp,jpg}).
// Explicit width/height reserve layout space (no CLS) and loading="lazy" keeps it
// out of the first-paint critical path.

// Asset sizes generated by the portrait pipeline.
const PORTRAIT_SIZES = [128, 256, 512] as const;
type PortraitSize = (typeof PORTRAIT_SIZES)[number];

// Snap a requested render size up to the nearest baked asset for crisp output
// (covers 2x DPI by serving a larger source when one exists).
function pickAsset(size: number): PortraitSize {
  return PORTRAIT_SIZES.find((s) => s >= size * 2) ?? PORTRAIT_SIZES[PORTRAIT_SIZES.length - 1];
}

export interface AvatarProps {
  /** Rendered square edge in CSS pixels. Defaults to 128. */
  size?: number;
  /** Alt text for the portrait. Defaults to an identity-forward description. */
  alt?: string;
  className?: string;
  /** Override lazy loading (e.g. "eager" above the fold). Defaults to "lazy". */
  loading?: "lazy" | "eager";
}

export default function Avatar({
  size = 128,
  alt = "Portrait of Jake Castillo",
  className = "",
  loading = "lazy",
}: AvatarProps) {
  const asset = pickAsset(size);

  return (
    <picture className={className}>
      <source srcSet={`/portrait/jake-${asset}.webp`} type="image/webp" />
      <img
        src={`/portrait/jake-${asset}.jpg`}
        alt={alt}
        width={size}
        height={size}
        loading={loading}
        decoding="async"
        className="block h-full w-full object-cover"
      />
    </picture>
  );
}
